# Generated by Django 6.0.1 on 2026-03-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='feature_icons/')),
            ],
        ),
    ]
